export const stages = [
    {
        id:0,
        name: 'Sentimientos',
        adress: require('../assets/memory/memory1/1.png'),
        image1: require('../assets/memory/memory1/1.png'),
        image2: require('../assets/memory/memory1/2.png'),
        image3: require('../assets/memory/memory1/3.png'),
        image4: require('../assets/memory/memory1/4.png'),
        image5: require('../assets/memory/memory1/5.png'),
        image6: require('../assets/memory/memory1/6.png'),
    },
    {
        id:1,
        name: 'Emociones',
        adress: require('../assets/memory/memory2/1.png'),
        image1: require('../assets/memory/memory2/1.png'),
        image2: require('../assets/memory/memory2/2.png'),
        image3: require('../assets/memory/memory2/3.png'),
        image4: require('../assets/memory/memory2/4.png'),
        image5: require('../assets/memory/memory2/5.png'),
        image6: require('../assets/memory/memory2/6.png'),
    },
    {
        id:2,
        name: 'Buenos Actos',
        adress: require('../assets/memory/memory3/1.png'),
        image1: require('../assets/memory/memory3/1.png'),
        image2: require('../assets/memory/memory3/2.png'),
        image3: require('../assets/memory/memory3/3.png'),
        image4: require('../assets/memory/memory3/4.png'),
        image5: require('../assets/memory/memory3/5.png'),
        image6: require('../assets/memory/memory3/6.png'),
    },
]